/*reate albums - The user can create albums
Edit albums
Delete albums
View albums
Upload photos
Edit photos
Delete photos
View photos
Download photos
Create comments
Edit comments
Delete comments
View comments
Like photos
Deslike photos
View likes
Share photos
Download photos
View user profiles
Edit user profiles
Create user accounts
Delete user accounts
Block user accounts
Unblock user accounts
Assign roles to users
Revoke roles from users
View activity logs
Export data
Import data
Search for content
Create tags
Edit tags
Delete tags
Sort photos by date, name or tags
Create collections
Edit collections
Delete collections
Add photos to collections
Remove photos from collections
View collections
Download collections
*/


INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (1, 'CREATE_ALBUMS', 'The user can create albums', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (2, 'EDIT_ALBUMS', 'The user can edit albums', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (3, 'DELETE_ALBUMS', 'The user can delete albums', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (4, 'VIEW_ALBUMS', 'The user can view albums', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (5, 'DOWNLOAD_ALBUMS', 'The user can download albums', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (6, 'UPLOAD_PHOTOS', 'The user can upload photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (7, 'EDIT_PHOTOS', 'The user can edit photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (8, 'DELETE_PHOTOS', 'The user can delete photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (9, 'VIEW_PHOTOS', 'The user can view photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (10, 'DOWNLOAD_PHOTOS', 'The user can download photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (11, 'CREATE_COMMENTS', 'The user can create comments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (12, 'EDIT_COMMENTS', 'The user can edit comments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (13, 'DELETE_COMMENTS', 'The user can delete comments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (14, 'VIEW_COMMENTS', 'The user can view comments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (15, 'LIKE_PHOTOS', 'The user can like photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (16, 'DESLIKE_PHOTOS', 'The user can deslike photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (17, 'VIEW_LIKES', 'The user can view likes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (18, 'SHARE_PHOTOS', 'The user can share photos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (19, 'VIEW_USER_PROFILES', 'The user can view user profiles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (20, 'EDIT_USER_PROFILES', 'The user can edit user profiles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (21, 'CREATE_USER_ACCOUNTS', 'The user can create user accounts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (22, 'DELETE_USER_ACCOUNTS', 'The user can delete user accounts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (23, 'BLOCK_USER_ACCOUNTS', 'The user can block user accounts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (24, 'UNBLOCK_USER_ACCOUNTS', 'The user can unblock user accounts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (25, 'ASSIGN_ROLES_TO_USERS', 'The user can assign roles to users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (26, 'REVOKE_ROLES_FROM_USERS', 'The user can revoke roles from users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (27, 'VIEW_ACTIVITY_LOGS', 'The user can view activity logs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (28, 'EXPORT_DATA', 'The user can export data', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (29, 'IMPORT_DATA', 'The user can import data', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (30, 'SEARCH_FOR_CONTENT', 'The user can search for content', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (31, 'CREATE_TAGS', 'The user can create tags', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (32, 'EDIT_TAGS', 'The user can edit tags', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (33, 'DELETE_TAGS', 'The user can delete tags', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (34, 'SORT_PHOTOS_BY_DATE_NAME_OR_TAGS', 'The user can sort photos by date, name or tags', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (35, 'CREATE_COLLECTIONS', 'The user can create collections', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (36, 'EDIT_COLLECTIONS', 'The user can edit collections', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (37, 'DELETE_COLLECTIONS', 'The user can delete collections', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (38, 'ADD_PHOTOS_TO_COLLECTIONS', 'The user can add photos to collections', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (39, 'REMOVE_PHOTOS_FROM_COLLECTIONS', 'The user can remove photos from collections', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (40, 'VIEW_COLLECTIONS', 'The user can view collections', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)
VALUES (41, 'DOWNLOAD_COLLECTIONS', 'The user can download collections', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO PERMISSIONS (ID, NAME, DESCRIPTION, CREATED_AT, UPDATED_AT, DELETED)



